### PR TITLE
Rails2 fix

### PR DESCRIPTION
**Pull request by Kimtaro**
Hi

I was having trouble loading 0.4.0-pre4 under Rails2, railties either missing or version mismatch. This fixed it for me at least.

I redid this pull request because I had a stray incorrect comment in there.

Cheers
Kim

### CODE REVIEW

**Comment by pjammer** [comment]
awesome.  How do i use it?  i guess i can add it to my current gem and worry about that later, but this pull is essential to using this gem as a consumer in a rails 2  appplication.

**Comment by Kimtaro** [comment]
Yes, you'll have to generate a local gem with this fix applied to use it.

```
$ gem build oauth-plugin.gemspec
$ gem install oauth-plugin-0.4.0.pre4.gem
```

**Comment by pjammer** [comment]
cool. i just went into the gem in dev here and added that plus i had to decouple a bunch of token.rb methods from .user  as I'm using another method.

i got most of it to work too, but now i just have to figure out this before_create :create_user nonsense... I think i have to define create_user in the ConsumerToken model.

anywhore, thanks man!

**Comment by nesquena** [comment]
Any updates on this? I would love to use the latest version with my Rails 2.3.11 app

**Comment by pjammer** [comment]
you may have better luck with omniauth and devise-oauth-provider depending on what you need (consumer or provider).

or update to 3.0.x, cause i did it with my 2.3.5 app and it's so much faster,

**Comment by nesquena** [comment]
devise-oauth-provider only works with devise is that right? We are using a custom authentication solution.

**Comment by pjammer** [comment]
lemme look, i tried like 4 over 4 days 3 months ago.... i could be getting it confused.

**Comment by pjammer** [comment]
gem 'devise', ">=1.3.3"
gem 'devise_oauth2_providable'

# gem 'omniauth'

#gem "oauth"
#gem "oauth-plugin", ">=0.4.0.pre4"
#gem "rack-oauth2"

In the end i used devise_oauth2_providable, and omniauth with my provider specs added from a repo i have on github, on the consumer app.

**Comment by buffym** [comment]
Looking for updates on this request as well. Trying to setup oauth with youtube API from my rails 2 app. Rails 3 not an option at this point. Thanks!

**Comment by pjammer** [comment]
buffym, could you use omniauth for consuming youtube?

**Comment by naoyamakino** [comment]
Looking for updates on this request as well. Currently we are using v0.3.14 but now our app is moving to use oauth2. I am getting this error message when I install 0.4.0-pre4, but it works until 0.4.0.pre2. Our rails is 2.3.14. Thanks!

**Pull request merged**
