### PR TITLE
Rails 4 support

### PR DESCRIPTION
**Pull request by tomhughes**
Add rails 4 support.

### CODE REVIEW

**Comment by codyrobbins** [comment]
+1

**Comment by tomhughes** [comment]
Added some more patches to replace deprecated methods with newer versions to avoid warnings with rails 4.

**Comment by mximos** [comment]
is the bug fixed?

**Comment by enragedginger** [comment]
It looks like it's still an issue. I'm running into the error: 'cannot load such file -- action_controller/request'.

**Comment by acellam** [comment]
I have corrected the see commit  'cannot load such file -- action_controller/request'.

 https://github.com/mistaguy/oauth-plugin/commit/849aed949d278d101dc2cbab877efdfd2c6fb9c1

**Comment by acellam** [comment]
A better fix to the  'cannot load such file -- action_controller/request'.
see https://github.com/mistaguy/oauth-plugin/commit/befd3d154c1eea5621105fef1be708e6dda9a569

**Comment by acellam** [comment]
The plugin has been generating the not supported "match" instead of "get" in routes.
see fix https://github.com/mistaguy/oauth-plugin/commit/9c46df6fe45e0693de5f8683415844e5045a157a

**Pull request merged**
