### PR TITLE
Search for Oauth2Token that are authorized and not invalidated in the Rack middleware

### PR DESCRIPTION
**Pull request by rymai**
Hi,

First, thanks for this plugin!

I was surprised that when using `OAuth::Controllers::ApplicationControllerMethods.oauthenticate`, every token were valid for authentication, even the invalidated ones!

So I think this patch fix this (I've updated the specs). I've also simplified a condition in `OAuth::Rack::OAuthFilter#oauth2_token` and the Guardfile to remove the deprecation notice.

Thanks!

### CODE REVIEW

**Comment by rymai** [comment]
Any activity here? :)

**Comment by pelle** [comment]
Sorry I've been really busy. I'm merging it in now and creating a release.

**Comment by pelle** [comment]
Done. Thank you very much. An important fix.

**Comment by rymai** [comment]
Thanks very much and thanks for the plugin, that's a really useful bootstrap! :)

**Pull request closed without merging**
